-- Italia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gianluigi','BUFFON','ITA','28/01/1978');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daniele','DE ROSSI','ITA','24/07/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrea','BARZAGLI','ITA','8/05/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Domenico','CRISCITO','ITA','30/12/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Riccardo','MONTOLIVO','ITA','18/01/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Giorgio','CHIELLINI','ITA','14/08/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Graziano','PELLE','ITA','15/07/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Matteo','DARMIAN','ITA','2/12/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ciro','IMMOBILE','ITA','20/02/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Giacomo','BONAVENTURA','ITA','22/08/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Antonio','CANDREVA','ITA','28/02/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stephan','EL SHAARAWY','ITA','27/10/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mattia','PERIN','ITA','10/11/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Federico','MARCHETTI','ITA','7/02/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marco','VERRATTI','ITA','5/11/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Angelo','OGBONNA','ITA','23/05/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Leonardo','BONUCCI','ITA','1/05/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Davide','ASTORI','ITA','7/01/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mattia','DE SCIGLIO','ITA','20/10/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alessandro','FLORENZI','ITA','11/03/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Manolo','Gabbiadini','ITA','26/11/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luca','Antonelli','ITA','11/02/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Simone','SCUFFET','ITA','31/05/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marco','PAROLO','ITA','25/01/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nicolo','BARELLA','ITA','7/02/1997');

-- Kazajstán
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Samat','Smakov','KAZ','8/12/1978');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandr','MOKIN','KAZ','19/06/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Renat','ABDULIN','KAZ','14/04/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yuriy','LOGVINENKO','KAZ','22/07/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','LORIYA','KAZ','31/10/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandr','KISLITSYN','KAZ','8/03/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tanat','NUSSERBAYEV','KAZ','1/01/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Azat','NURGALIYEV','KAZ','30/06/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bauyrzhan','ISLAMKHAN','KAZ','23/02/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Dmitriy','SHOMKO','KAZ','19/03/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Sergey','Khizhnichenko','KAZ','17/07/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Viktor','DMITRENKO','KAZ','4/04/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yeldos','AKHMETOV','KAZ','01/06/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aleksei','Shchetkin','KAZ','21/05/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Samat','OTARBAYEV','KAZ','18/02/1990');

-- Kosovo
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Adis','NURKOVIC','BIH','1/01/1999');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alban','MEHA','ALB','26/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Valon','BERISHA','NOR','7/02/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Albert','Bunjaku','SUI','29/11/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Besart','Berisha','ALB','1/01/1999');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Samir','UJKANI','ALB','5/07/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Erton','Fejzullahu','SWE','7/02/1985');

-- Liechtenstein
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Peter','JEHLE','LIE','22/01/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Franz','BURGMEIER','LIE','7/04/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','BUECHEL','LIE','19/02/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Philippe','ERNE','LIE','14/12/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Benjamin','BUECHEL','LIE','4/07/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cengiz','BICER','LIE','11/12/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yves','OEHRI','LIE','15/03/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michele','POLVERINO','LIE','6/09/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','RECHSTEINER','LIE','1/01/1999');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daniel','KAUFMANN','LIE','22/12/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ivan','QUINTANS','LIE','15/10/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Sandro','Wieser','LIE','3/02/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nicolas','HASLER','LIE','4/05/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Niklas','KIEBER','LIE','4/03/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Philipp','OSPELT','LIE','7/10/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Robin','GUBSER','LIE','17/04/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Seyhan','YILDIZ','LIE','30/04/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andreas','CHRISTEN','LIE','29/08/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Sandro','WOLFINGER','LIE','24/08/1991');

-- Lituania
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Deividas','CESNAUSKIS','LTU','30/06/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tomas','Radzinevicius','LTU','5/06/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tomas','MIKUCKIS','LTU','13/01/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Linas','Klimavicius','LTU','10/04/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arunas','KLIMAVICIUS','LTU','5/10/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Darvydas','SERNAS','LTU','22/07/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vytautas','Luksa','LTU','14/08/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tadas','KIJANSKAS','LTU','6/09/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vaidas','SLAVICKAS','LTU','26/02/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ernestas','SETKUS','LTU','25/05/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Valdemar','BOROVSKIJ','LTU','2/05/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vytautas','ANDRIUSKEVICIUS','LTU','8/10/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Deivydas','MATULEVICIUS','LTU','8/04/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arvydas','NOVIKOVAS','LTU','18/12/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Egidijus','VAITKUNAS','LTU','8/07/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Emilijus','ZUBAS','LTU','10/07/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Karolis','CHVEDUKAS','LTU','21/04/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Georgas','FREIDGEIMAS','LTU','10/08/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martynas','Dapkus','LTU','16/02/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Fiodor','Cernych','LTU','21/05/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vaidas','Silenas','LTU','16/07/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lukas','Spalvis','LTU','27/07/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arturas','ZULPA','LTU','10/06/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mantas','Kuklys','LTU','10/06/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nerijus','VALSKIS','LTU','4/08/1987');

-- Luxenburgo
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aurelien','JOACHIM','LUX','10/08/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mario','MUTSCH','LUX','3/09/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daniel','DA MOTA','LUX','11/08/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stefano','BENSI','LUX','11/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lars','GERSON','LUX','5/02/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jonathan','JOUBERT','LUX','12/09/1979');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ben','PAYAL','LUX','8/09/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mathias','JAENISCH','LUX','27/08/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kevin','MALGET','LUX','15/01/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tom','LATERZA','LUX','9/05/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Dwayn','HOLTER','LUX','15/06/1995');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Maurice','DEVILLE','LUX','31/07/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Laurent','JANS','LUX','5/08/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Chris','PHILIPPS','LUX','8/03/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ricardo Aleixo','Delgado','LUX','22/02/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nicolo','BARELLA','LUX','7/02/1986');

-- Letonia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andris','VANINS','LVA','30/04/1980');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aleksejs','VISNAKOVS','LVA','30/02/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Girts','Karlsons','LVA','7/06/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Olegs','LAIZANS','LVA','28/04/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ivans','LUKJANOVS','LVA','24/01/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kaspars','GORKSS','LVA','6/11/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Artjoms','RUDNEVS','LVA','13/01/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vladimirs','KAMESS','LVA','28/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Artis','LAZDINS','LVA','3/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vitalijs','MAKSIMENKO','LVA','8/12/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arturs','ZJUZINS','LVA','18/06/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Valerijs','SABALA','LVA','12/08/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kaspars','IKSTENS','LVA','5/06/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kaspars','DUBRA','LVA','20/12/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Igors','TARASOVS','LVA','16/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Deniss','Rakels','LVA','20/08/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vladislavs','GABOVS','LVA','13/07/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vitalijs','JAGODINSKIS','LVA','28/02/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arturs','Karasauskas','LVA','29/01/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Eduards','Visnakovs','LVA','10/05/1990');

-- Moldavia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Victor','GOLOVATENCO','MDA','28/04/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vitalie','BORDIAN','MDA','11/08/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandru','GATCAN','MDA','27/03/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Serghei','PASCENCO','MDA','18/12/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Igor','ARMAS','MDA','14/07/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vadym','BOLOKHAN','MDA','1/01/1999');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Igor','BUGAEV','MDA','26/06/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nicolai','CALANCEA','MDA','1/01/1999');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Eugeniu','CEBOTARU','MDA','16/10/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandru','EPUREANU','MDA','27/09/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stanislav','NAMASCO','MDA','10/11/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Igor','TIGIRLAS','MDA','24/02/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Igor','PICUSCIAC','MDA','27/03/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Artur','Ionita','MDA','17/08/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Petru','RACU','MDA','17/07/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandr','Pascenco','MDA','28/05/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandru','Dedov','MDA','26/07/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Eugeniu','SIDORENCO','MDA','19/03/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ion','JARDAN','MDA','10/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandru','Antoniuc','MDA','23/05/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ilie','CEBANU','MDA','29/12/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gheorghe','Andronic','MDA','25/09/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrei','COJOCARI','MDA','21/01/1987');

-- ARY de Macedonia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Goran','PANDEV','MKD','27/07/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ivan','Trickovski','MKD','18/04/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daniel','MOJSOV','MKD','25/12/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vance','Sikov','MKD','19/07/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Besart','Ibraimi','MKD','1/01/1999');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arijan','ADEMI','MKD','29/05/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ferhan','Hasani','MKD','18/06/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','BOGATINOV','MKD','26/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stefan','RISTOVSKI','MKD','12/02/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stefan','SPIROVSKI','MKD','23/08/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aleksandar','TRAJKOVSKI','MKD','5/09/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ostoja','STJEPANOVIC','MKD','17/01/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Adis','JAHOVIC','MKD','18/03/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','MITOV NILSSON','MKD','12/01/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','BABUNSKI','MKD','1/03/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ezdjan','ALIOSKI','MKD','12/02/1992');

-- Malta
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexander','MUSCAT','MLT','14/12/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gareth','SCIBERRAS','MLT','29/03/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michael','MIFSUD','MLT','17/04/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Justin','HABER','MLT','9/06/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Roderick','BRIFFA','MLT','24/08/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrew','HOGG','MLT','2/03/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Henry','BONELLO','MLT','13/10/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jonathan','CARUANA','MLT','24/07/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrei','AGIUS','MLT','12/08/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Clayton','FAILLA','MLT','8/01/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ryan','CAMILLERI','MLT','7/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Steve','Borg','MLT','15/05/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mark','Scerri','MLT','16/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ryan','FENECH','MLT','20/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Paul','FENECH','MLT','20/12/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andre','SCHEMBRI','MLT','27/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Samuel','MAGRI','MLT','30/03/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bjorn','KRISTENSEN','MLT','75/04/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Rowen','MUSCAT','MLT','15/06/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jacob','BORG','MLT','2/05/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Clifford','GATT','MLT','9/02/1988');

-- Montenegro
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vukasin','POLEKSIC','MNE','30/08/1982'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mirko','VUCINIC','MNE','1/10/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mladen','BOZOVIC','MNE','1/08/1984'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Elsad','ZVEROTIC','MNE','30/10/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stevan','JOVETIC','MNE','2/11/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marko','BASA','MNE','29/12/1982'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Fatos','BECIRAJ','MNE','5/05/1988'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nemanja','Nikolic','MNE','1/01/1988'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Zarko','TOMASEVIC','MNE','22/02/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nebojsa','KOSOVIC','MNE','24/02/1995'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stefan','SAVIC','MNE','8/01/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luka','DJORDJEVIC','MNE','9/07/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Srefan','MUGOSA','MNE','26/02/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marko','BAKIC','MNE','1/11/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nikola','VUKCEVIC','MNE','13/12/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marko','Vesovic','MNE','28/08/1991');

-- Paises Bajos
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Maarten','STEKELENBURG','NED','22/09/1982'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arjen','ROBBEN','NED','23/01/1984'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Wesley','SNEIJDER','NED','9/06/1984'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ryan','BABEL','NED','19/12/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Robin','VAN PERSIE','NED','6/08/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michel','VORM','NED','20/10/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Siem','DE JONG','NED','28/01/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jeremain','LENS','NED','24/11/1987'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stefan','DE VRIJ','NED','5/02/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Joel','VELTMAN','NED','15/01/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Sergio','PADT','NED','6/06/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Patrick','VAN AANHOLT','NED','29/08/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jeffrey','BRUMA','NED','13/11/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daryl','JANMAAT','NED','22/07/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nick','VIERGEVER','NED','3/08/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daley','BLIND','NED','9/03/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Leroy','FER','NED','5/01/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kevin','STROOTMAN','NED','13/02/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Georginio','Wijnaldum','NED','11/11/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bas','Dost','NED','31/05/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luuk','DE JONG','NED','27/08/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Terence','KONGOLO','NED','14/02/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Karim','REKIK','NED','2/12/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jetro','WILLEMS','NED','30/03/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nathan','AKE','NED','18/02/1995'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Memphis','DEPAY','NED','13/02/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tonny','Vilhena','NED','3/01/1995'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luciano','NARSINGH','NED','13/09/1990'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jeroen','ZOET','NED','6/01/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jordy','CLASIE','NED','27/06/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bruno','MARTINS INDI','NED','8/02/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jasper','CILLESSEN','NED','22/04/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marco','VAN GINKEL','NED','1/12/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Davy','KLAASSEN','NED','21/02/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Quincy','PROMES','NED','4/01/1992'); 

-- Irlanda del Norte
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Roy','CARROLL','NIR','30/09/1977');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aaron','Hughes','NIR','8/11/1979');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alan','MANNUS','NIR','19/05/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Steven','DAVIS','NIR','1/01/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michael','McGOVERN','NIR','12/07/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Chris','BRUNT','NIR','14/12/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gareth','McAuley','NIR','5/12/1979');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kyle','Lafferty','NIR','16/09/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jonny','EVANS','NIR','3/01/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jamie','WARD','NIR','12/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Niall','MCGINN','NIR','20/07/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ryan','McGIVERN','NIR','8/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Corry','EVANS','NIR','30/07/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','William','GRIGG','NIR','3/06/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Oliver','NORWOOD','NIR','12/04/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Rory','McARDLE','NIR','1/05/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lee','HODSON','NIR','2/10/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Craig','CATHCART','NIR','6/02/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Shane','FERGUSON','NIR','12/07/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Trevor','CARSON','NIR','5/03/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ryan','McLAUGHLIN','NIR','30/09/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','George','SAVILLE','NIR','1/06/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Daniel','LAFFERTY','NIR','18/05/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Josh','Magennis','NIR','15/08/1990');

-- Noruega
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Rune','ALMENNING JARSTEIN','NOR','29/09/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tore','REGINIUSSEN','NOR','10/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Orjan','Nyland','NOR','10/09/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','André','Hansen','NOR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tom','Hogli','NOR','24/02/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','Linnes','NOR','1/01/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stian','Ringstad','NOR','1/01/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Brede','Hangeland','NOR','20/06/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Håvard','Nordtveit','NOR','21/06/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Johan','Ladre Bjordal','NOR','5/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vegard','Forren','NOR','16/02/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stefan','Johansen','NOR','8/01/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jone','Samuelsen','NOR','6/07/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Morten','Gamst Pedersen','NOR','8/09/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexander','Tettyusky','NOR','4/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Valon','Berisha','NOR','7/02/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Per','CILJAN SKJELBRED','NOR','16/06/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Joshua','King','NOR','15/01/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','Odegaard','NOR','17/12/1998');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bjorn','Johnsen','NOR','6/11/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tarik','Elyounoussi','NOR','23/02/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Anders','Konradsen','NOR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ruben','Yttergård Jenssen','NOR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','André','Danielsen','NOR','1/01/1990');

-- Polonia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Wojciech','Szczesny','POL','18/04/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Artur','Boruc','POL','20/02/1980');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lukasz','Fabianski','POL','18/04/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michal','Pazdan','POL','21/09/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Artur','Jedrzejczyk','POL','4/09/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Thiago','Rangel Cionek','POL','21/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Igor','Lewczuk','POL','30/05/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kamil','Glik','POL','3/02/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bartosz','Salamon','POL','1/05/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lukasz','Piszczek','POL','3/06/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tomasz','Jodlowiec','POL','8/09/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Karol','Linetty','POL','2/02/1995');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Grzegorz','Krychowiak','POL','29/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kamil','Grosicki','POL','18/06/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Maciej','Rybus','POL','19/08/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jakub','Blaszczykowski','POL','14/12/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Piotr','Zielinski','POL','20/05/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bartosz','Kapustka','POL','23/12/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Arkadiusz','Milik','POL','28/02/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Robert','Lewandowski','POL','21/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lukasz','Teodorczyk','POL','3/06/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kamil','Wilczek','POL','14/01/1988');

-- Portugal
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Rui','Patricio','POR','15/02/1988'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','José','Sá','POR','17/01/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Beto','Bastos','POR','1/05/1982'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bruno','Alves','POR','27/11/1981'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Képler','Lima Ferreira','POR','26/02/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luís','Novo Neto','POR','26/05/1988'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Raphael','Guerreiro','POR','22/12/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','José','Fonte','POR','22/12/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nélson','Semedo','POR','16/12/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Eliseu','Pereira','POR','1/10/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cédric','Soares','POR','31/08/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Joao','Moutinho','POR','15/09/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Danilo','Pereira','POR','9/09/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','William','Carvalho','POR','7/04/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','André','Gomes','POR','30/07/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Pizzi','Fernandes','POR','6/10/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Adrien','Silva','POR','15/03/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cristiano','Ronaldo','POR','5/02/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','André','Silva','POR','6/11/1995'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bernardo','Silva','POR','10/08/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luis','Almeida','POR','17/11/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gelson','Martins','POR','11/05/1995'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ricardo','Quaresma','POR','26/09/1983'); 

-- Rumania
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Costel','Pantilimon','ROU','1/02/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ciprian','Tatarusanu','ROU','9/02/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Silviu','Lung Junior','ROU','4/06/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Romario','Benzar','ROU','26/03/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cosmin','Moti','ROU','3/12/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vlad','Chiriches','ROU','14/11/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Iasmin','Latovlevici','ROU','11/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alin','Tosca','ROU','14/03/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Dragos','Grigore','ROU','7/09/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cristian','Sapunaru','ROU','5/04/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandru','Chipciu','ROU','18/05/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Adrian','Popa','ROU','24/07/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nicolae','Stanciu','ROU','7/05/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexandru','Maxim','ROU','8/07/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrei','Prepelita','ROU','8/12/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Razvan','Marin','ROU','23/05/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Florin','Andone','ROU','11/04/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Claudiu','Keseru','ROU','2/12/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bogdan','Stancu','ROU','28/06/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Denis','Alibec','ROU','5/01/1991');

-- Escocia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Craig','Gordon','SCO','31/12/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kieran','Tierney','SCO','5/06/1997');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrew','Robertson','SCO','11/03/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Christophe','Berra','SCO','31/01/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Charles','Mulgrew','SCO','6/03/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','James','Morrison','SCO','25/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stuart','Armstrong','SCO','30/03/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Scott','Brown','SCO','25/06/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Leigh','Griffiths','SCO','20/08/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Robert','Snodgrass','SCO','7/09/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ikechi','Anya','SCO','3/01/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','Marshall','SCO','5/03/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','James','McArthur','SCO','7/10/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Steven','Naismith','SCO','14/09/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Barry','Bannan','SCO','1/12/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Darren','Fletcher','SCO','1/02/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','James','Forrest','SCO','7/07/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Russell','Martin','SCO','4/01/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Chris','Martin','SCO','4/11/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ryan','Fraser','SCO','4/02/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tom','Cairney','SCO','20/01/1991');

-- San Marino
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aldo','Simoncini','SMR','30/08/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Danilo','Rinaldi','SMR','18/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Adolfo','Hirsch','SMR','31/01/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Giacomo','Muraccini','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Elia','Benedettini','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Davide','Cesarini','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrea','Grandoni','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michele','Cevoli','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Fabio','Vitaioli','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alessandro','Della Valle','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cristian','Brolli','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alex','Gasperoni','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michael','Battistini','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Maicol','Berretti','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alessandro','Golinucci','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Michele','Cervellini','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luca','Tosi','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mattia','Stefanelli','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Fabio','Tomassini','SMR','1/01/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marco','Bernardi','SMR','1/01/1990');

-- Serbia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vladimir','Stojkovic','SRB','28/07/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ivan','Obradovic','SRB','25/07/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nenad','Tomovic','SRB','30/08/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nemanja','Gudelj','SRB','16/11/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Branislav','Ivanovic','SRB','11/02/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Zoran','Tosic','SRB','28/04/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Radosav','Petrovic','SRB','8/03/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aleksandar','Mitrovic','SRB','16/09/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Dusan','Tadic','SRB','20/11/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aleksandar','Kolarov','SRB','10/11/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nemanja','Matic','SRB','1/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Darko','Brasanac','SRB','12/02/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Luka','Milivojević','SRB','7/04/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Filip','Kostic','SRB','1/11/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andrija','Zivkovic','SRB','11/07/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ljubomir','Fejsa','SRB','14/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bojan','Krkic','SRB','28/08/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Adem','Ljajic','SRB','29/09/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lazar','Markovic','SRB','2/03/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Zeljko','Brkic','SRB','9/07/1986');

-- Suiza
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yann','Sommer','SUI','17/12/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marwin','Hitz','SUI','18/09/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Roman','Burki','SUI','14/11/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Stephan','Lichtsteiner','SUI','16/01/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Fabian','Schar','SUI','20/12/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Timm','Klose','SUI','9/05/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nico','Elvedi','SUI','30/09/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Renato','Steffen','SUI','3/11/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Blerim','Dzemaili','SUI','12/04/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gelson','Fernandes','SUI','2/09/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Denis','Zakaria','SUI','20/11/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Xherdan','Shaqiri','SUI','10/10/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Reto','Ziegler','SUI','16/01/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Granit','Xhaka','SUI','27/09/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Edimilson','Fernandes','SUI','15/04/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Shani','Tarashaj','SUI','7/02/1995');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Breel','Embolo','SUI','14/02/1997');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Valentin','Stocker','SUI','12/04/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Admir','Mehmedi','SUI','16/03/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Eren','Derdiyok','SUI','12/06/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Haris','Seferovic','SUI','22/02/1992');

-- Eslovaquia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marek','BAKOS','SVK','15/04/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','SKRTEL','SVK','15/12/1984'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Viktor','PECOVSKY','SVK','24/05/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jan','DURICA','SVK','10/12/1981'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Peter','PEKARIK','SVK','30/10/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Tomas','Hubocan','SVK','17/09/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marek','HAMSIK','SVK','27/07/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kornel','SALATA','SVK','24/01/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Matúš','KOZÁCIK','SVK','27/12/1983'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vladimir','WEISS','SVK','30/11/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','DUBRAVKA','SVK','15/01/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Robert','PICH','SVK','12/11/1988'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Róbert','MAK','SVK','8/03/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Lukas','PAUSCHEK','SVK','9/12/1992');

-- Eslovenia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jan','Oblak','SVN','7/01/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nejc','Skubic','SVN','13/06/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bostjan','Cesar','SVN','9/07/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Branko','Ilic','SVN','6/02/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Josip','Ilicic','SVN','29/01/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jasmin','Kurtic','SVN','10/01/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Zlatan','Ljubijankic','SVN','15/12/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Valter','Birsa','SVN','7/08/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Milivoje','Novakovic','SVN','18/05/1979');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Bojan','Jokic','SVN','17/05/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andraz','Kirm','SVN','6/09/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Nejc','Pecnik','SVN','3/01/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kevin','Kampl','SVN','9/10/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Rene','Krhin','SVN','21/05/1990');

-- Suecia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andreas','GRANQVIST','SWE','16/04/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Sebastian','LARSSON','SWE','6/06/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Oscar','WENDT','SWE','24/10/1985'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Marcus','BERG','SWE','17/08/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mikael','LUSTIG','SWE','13/12/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ola','TOIVONEN','SWE','3/07/1986'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Martin','OLSSON','SWE','17/05/1988'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Albin','EKDAL','SWE','28/07/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Kristoffer','NORDFELDT','SWE','23/06/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jimmy','DURMAZ','SWE','22/03/1989'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Linus','WAHLQVIST','SWE','11/11/1996'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Oscar','HILJEMARK','SWE','28/06/1992'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Pontus','JANSSON','SWE','13/02/1991'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Alexander','FRANSSON','SWE','2/04/1994'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andreas','LINDE','SWE','24/07/1993'); 
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ken','SEMA','SWE','30/09/1993'); 

-- Turquia
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Volkan','Babacan','TUR','11/08/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Atila','Turan','TUR','10/04/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','İsmail','Koybasi','TUR','10/07/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Serdar','Aziz','TUR','23/10/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Okay','Yokuslu','TUR','9/03/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ozan','Tufan','TUR','23/03/1995');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Selcuk','Inan','TUR','10/02/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Cenk','Tosun','TUR','7/06/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Hakan','Calhanoglu','TUR','8/02/1994');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Oguzhan','Ozyakup','TUR','23/09/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Enes','Unal','TUR','10/05/1997');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yunus','Malli','TUR','24/02/1992');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Çaglar','Soyuncu','TUR','23/03/1996'); 

-- Ucrania
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Denys','Boyko','UKR','29/01/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Mykola','Morozyuk','UKR','17/01/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yevhen','Jacheridi','UKR','28/07/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Anatoliy','Timoshchuk','UKR','30/03/1979');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Oleksandr','Kucher','UKR','22/10/1982');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Taras','Stepanenko','UKR','8/08/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andriy','Yarmolenko','UKR','23/10/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Román','Zozulia','UKR','17/11/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Viktor','Kovalenko','UKR','14/02/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yevhen','Konoplyanka','UKR','29/09/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yevhen','Seleznyov','UKR','20/07/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andriy','Pyatov','UKR','28/06/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Viacheslav','Shevchuk','UKR','13/05/1979');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ruslan','Rotan','UKR','29/10/1981');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Dmitro','Chigrinskiy','UKR','7/11/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Serhiy','Sydorchuk','UKR','2/05/1991');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Artem','Fedetskiy','UKR','26/04/1985');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Denís','Garmash','UKR','19/04/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Yaroslav','Rakitski','UKR','3/08/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Oleksandr','Zinchenko','UKR','15/12/1996');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Vladlen','Yurchenko','UKR','22/01/1994');

-- Gales
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Wayne','Hennessey','WAL','24/01/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Owain','Williams','WAL','17/03/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ashley','Williams','WAL','23/08/1984');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','James','Chester','WAL','23/01/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','James','Collins','WAL','23/08/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Ben','Davies','WAL','24/04/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Neil','Taylor','WAL','7/02/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Chris','Gunter','WAL','21/06/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Andy','King','WAL','29/10/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Aaron','Ramsey','WAL','26/12/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Joe','Allen','WAL','14/03/1990');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Joe','Ledley','WAL','23/01/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Jonny','Williams','WAL','9/10/1993');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','Vaughan','WAL','18/02/1983');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','Edwards','WAL','3/02/1986');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','David','Cotterill','WAL','4/12/1987');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Gareth','Bale','WAL','16/07/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Sam','Vokes','WAL','21/10/1989');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Simon','Church','WAL','10/12/1988');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','George','Williams','WAL','7/09/1995');
INSERT INTO Personas (cod_persona, nom_persona, ape_persona, cod_pais, f_nac ) VALUES ('60001','Hal','Robson','WAL','21/05/1989');
